import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

export const metadata = {
  title: "Clothing-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="mx-5 lg:mx-16">
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
